import React, {useEffect, useState, ReactNode} from 'react'
import Head from "next/head"
import THeader from "@/components/template/admin/header"
import Navbar from "@/components/template/admin/navbar"
import Sidebar from "@/components/template/admin/sidebar"
import Footer from "@/components/template/footer"
import {useToogleSidebarPanel} from "@/utils/stores/sidebarPanel";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

interface TemplatePros {
    children: ReactNode;
}

const Template: React.FC<TemplatePros> = ({children}) => {
    const {active} = useToogleSidebarPanel();
    const [isMounted, setIsMounted] = useState(false);
    useEffect(() => { 
        if (isMounted) {
            if (active) {
                document.body.className = '';
            } else {
                document.body.className = 'toggle-sidebar';
            }

            toast('🚀 Halaman Selesai dimuat', {
                position: "top-center",
                autoClose: 3000,
                hideProgressBar: false,
                closeOnClick: true,
                pauseOnHover: true,
                draggable: true,
                progress: undefined,
                theme: "light",
            });
        } else {
            setIsMounted(true);
        }
    },[active, isMounted])
    return (
        <>
            <Head>
                <title>Panel MA ZAHA 1</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/assets/img/logo.png"/>
            </Head>
            <div style={{backgroundColor: 'white'}}>
                <THeader>
                    <Navbar/>
                </THeader>
                <Sidebar/>
                <main id="main" className="main bg-[#f8fcfc]">
                    <ToastContainer />
                    {children}
                </main>
            </div>
            <Footer/>
        </>
    )
}
export default Template;
