import React, {useState, useEffect, ReactNode} from 'react'
import Head from "next/head"
import {useToogleSidebarPanel} from "@/utils/stores/sidebarPanel";
import Topbar from "@/components/template/santri/topbar";

interface TemplatePros {
    children: ReactNode;
}

const Template: React.FC<TemplatePros> = ({children}) => {
    const {active} = useToogleSidebarPanel();
    useEffect(() => {
        if (active) {
            document.body.className = '';
        } else {
            document.body.className = 'toggle-sidebar';
        }
    });
    return (
        <>
            <Head>
                <title>Santri MA ZAHA 1</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/assets/img/logo.png"/>
            </Head>
            <div style={{backgroundColor: 'white'}}>
                <Topbar/>
                <div className="flex justify-center px-10 md:px-72 py-3">
                {children}
                </div>
            </div>
        </>
    )
}
export default Template;
