import React, {useState, useEffect, ReactNode} from 'react'
import Head from "next/head"
import THeader from "@/components/template/admin/header"
import Navbar from "@/components/template/admin/navbar"
import Sidebar from "@/components/template/admin/sidebar"
import Footer from "@/components/template/footer"

interface TemplatePros {
    children: ReactNode;
}

const Template: React.FC<TemplatePros> = ({children}) => {
    return (
        <>
            <Head>
                <title>Panel MA ZAHA 1</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/assets/img/logo.png"/>
            </Head>
            <div style={{ backgroundColor: 'white' }}>
                <THeader>
                    <Navbar/>
                </THeader>
                <Sidebar/>
                {children}
            </div>
            <Footer/>
        </>
    )
}
export default Template;
